name: AutoMod
version: 0.11
main: uk.co.jacekk.bukkit.automod.AutoMod
softdepend: [LogBlock, NoCheat, MineBans]
commands:
    build:
        description: Requests build permissions to be restored
        usage: /<command>
    list:
        description: Manage the block and trusted player lists
        usage: /<command>
    data:
        description: Prints the data that caused a player to be placed on the block list
        usage: /<command> [player_name]
    trustallplayers:
        description: Adds all of the players that have ever been on the server to the trusted list.
        usage: /<command>